excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://fprisse.github.io
title: TinyPress
tagline: for we it lasen will
description: Hier schrijf ik af een toe een verhaaltje
paginate: 5